using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DoorController : MonoBehaviour {

    public Animator anim;

	// Use this for initialization
	void Start () {
        anim = GetComponent<Animator>();
	}
	
	// Update is called once per frame
	void Update () {
		
	}

    private void OnTriggerEnter(Collider other)
    {
        if (other.tag == "character")
        {
            anim.SetBool("isOpen", true);
        }
        if (other.tag == "user")
        {
            Application.LoadLevel(1);
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.tag == "character")
        {
            anim.SetBool("isOpen", false);
        }
    }
}
